const press = [
	{
		title: 'Violence at Sea: How Terrorists, Insurgents, and Other Extremists Exploit the Maritime Domain',
		publisher: 'Published by Stable Seas, One Earth Future.',
		year: '2020.',
		author: 'Authored with Christopher Faulkner (University of Central Florida), Curtis Bell, Meghan Curran, Tyler Lycan, and Jay Benson (all Stable Seas)',
		category: 'major_regional_thematic_report',
	},
	{
		title: 'Stable Seas: Bay of Bengal.',
		publisher: 'Published by Stable Seas, One Earth Future.',
		year: '2020.',
		author: 'Authored with Jay Benson, Curtis Bell, Lydelle Joubert, Maisie Pigeon, Asyura Salleh (all stable seas), Gayathri Iyer, (Observer Research Foundation), M J Rahman (World Fish), and M A Wahab (World Fish)',
		category: 'major_regional_thematic_report',
	},
	{
		title: 'Black Sea Synergy: A Holistic Approach to Maritime Security.',
		publisher: 'Published by Europeum institute of European Policy.',
		year: '2022.',
		author: 'Author.',
		category: 'policy_brief_publication',
	},
	{
		title: 'Addressing Maritime Security in Southeast Asia',
		publisher: 'Published by Stable Seas, One Earth Future.',
		year: '2021.',
		author: 'Author.',
		category: 'policy_brief_publication',
	},

	{
		title: 'BARMM Blue Economy: Policy Proposals For the Bangsamoro Autonomous Region in Muslim Mindanao.',
		publisher: 'Published by Stable Seas, One Earth future.',
		year: '2020.',
		author: 'Author.',
		category: 'policy_brief_publication',
	},
	{
		title: 'Challenges and Solutions for Maritime Security in the Indian Ocean.',
		publisher: 'Published by Stable Seas.',
		year: '2020',
		author: 'Author.',
		category: 'policy_brief_publication',
	},
	{
		title: 'A Pathway to Policy Change: Improving Philippine Fisheries, Blue Economy, and Maritime Law Enforcement in the Sulu and Celebes Seas.',
		publisher: 'Stable Seas, One Earth Future. 2019.',
		author: 'Author.',
		category: 'policy_brief_publication',
	},

	{
		title: 'Opioid Smuggling in the Black Sea.',
		publisher: 'Published by Eurasian Review.',
		year: '2022.',
		author: 'Author',
		category: 'open_editorial',
	},

	{
		title: 'The Hungarian Ukrainian Schism.',
		publisher: ' Published by Real Clear Defense.',
		year: '2022.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'Moving Forward: Japan’s Maritime Policy Trajectory in the Philippines.',
		publisher: 'Published by Analyzing War.',
		year: '2021.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'Deconstructing Abu Sayyaf’s Resilience to Counter-Insurgency Operations',
		publisher: 'The Diplomat,',
		year: '2021',
		category: 'open_editorial',
		author: 'Author.',
	},
	{
		title: 'Countering Maritime Drug Trafficking in Bangladesh’s Coastal Waters.',
		publisher: 'Published by Stable Seas, One earth future.',
		year: '2020.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'A South Pacific Island-Led Approach to Regional Maritime Security.',
		publisher: 'Published by Center for International Maritime Security.',
		year: '2020.',
		author: 'Author',
		category: 'open_editorial',
	},
	{
		title: 'Thailand’s Deep South Insurgencies: Exploiting the Maritime Domain.',
		publisher: 'Published by The Diplomat.',
		year: '2020.',
		author: 'Author',
		category: 'open_editorial',
	},
	{
		title: 'Using Geospatial Data to Improve Maritime Domain Awareness in the Sulu and Celebes Seas.',
		publisher: 'Published by Center for International Maritime Security.',
		year: '2020.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'A Collaborative Approach to Improving Maritime Security in the Bay of Bengal.',
		publisher: 'Published by Stable Seas, One Earth Future.',
		year: '2020.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'Tamil Sea Tigers: Exploiting the Maritime Domain.',
		publisher: 'Published by Stable Sea, One Earth Future.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'Engaging With Local Stakeholders to Improve Maritime Security and Governance.',
		publisher: 'Published by Modern Diplomacy.',
		year: '2020.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'Japan’s Contributions to Maritime Stability in the Bay of Bengal.',
		publisher: 'Published by East Asia Forum.',
		year: '2020.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'How a Myanmar Coast Guard Will Contribute to Coastal Stability.',
		publisher: 'Published by The Diplomat.',
		year: '2020.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'Community Engagement: Improving Maritime Domain Awareness in the Bay of Bengal.',
		publisher: 'Published by Stable Seas, One Earth Future.',
		year: '2020',
		author: 'Author',
		category: 'open_editorial',
	},
	{
		title: 'The Future of Philippine Maritime Enforcement.',
		publisher: 'Published by ASEAN Post. 2019.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'Deterrence and Inclusivity in the South China Sea.',
		publisher: 'Published by Global Politics Magazine. 2019.',
		author: 'Author.',
		category: 'open_editorial',
	},
	{
		title: 'An Advisory Capacity: The Wider Ramifications of Security Force Assistance Brigades in Afghanistan.',
		publisher: 'Published by Small Wars Journal. 2019.',
		author: 'Author.',
		category: 'open_editorial',
	},
];

export default press;
